version: '3'
services:
  redis1:
      image: "redis"
      ports:
        - "63791:6379"
      networks:
        - cluster
  redis2:
      image: "redis"
      ports:
        - "63792:6379"
      networks:
        - cluster
  redis3:
      image: "redis"
      ports:
        - "63793:6379"
      networks:
        - cluster
  redis4:
      image: "redis"
      ports:
        - "63794:6379"
      networks:
        - cluster
  redis5:
      image: "redis"
      ports:
        - "63795:6379"
      networks:
        - cluster
  redis6:
      image: "redis"
      ports:
        - "63796:6379"
      networks:
        - cluster

networks:
  cluster:
    external: true